name: Run tests
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.11'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: Install dev dependencies
        run: |
          python3 -m pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest
